//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTMCL.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Url {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Url() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTMCL.Resources.Url", typeof(Url).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 http://bmclapi.bangbang93.com/ 的當地語系化字串。
        /// </summary>
        internal static string URL_DOWNLOAD_bangbang93 {
            get {
                return ResourceManager.GetString("URL_DOWNLOAD_bangbang93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://s3.amazonaws.com/Minecraft.Download/ 的當地語系化字串。
        /// </summary>
        internal static string URL_DOWNLOAD_BASE {
            get {
                return ResourceManager.GetString("URL_DOWNLOAD_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://mirrors.rapiddata.org/Minecraft.Download/ 的當地語系化字串。
        /// </summary>
        internal static string URL_DOWNLOAD_rapiddata {
            get {
                return ResourceManager.GetString("URL_DOWNLOAD_rapiddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://bmclapi2.bangbang93.com/libraries/ 的當地語系化字串。
        /// </summary>
        internal static string URL_LIBRARIES_bangbang93 {
            get {
                return ResourceManager.GetString("URL_LIBRARIES_bangbang93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://libraries.minecraft.net/ 的當地語系化字串。
        /// </summary>
        internal static string URL_LIBRARIES_BASE {
            get {
                return ResourceManager.GetString("URL_LIBRARIES_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://mirrors.rapiddata.org/libraries.minecraft.net/ 的當地語系化字串。
        /// </summary>
        internal static string URL_LIBRARIES_rapiddata {
            get {
                return ResourceManager.GetString("URL_LIBRARIES_rapiddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://bmclapi2.bangbang93.com/assets/ 的當地語系化字串。
        /// </summary>
        internal static string URL_RESOURCE_bangbang93 {
            get {
                return ResourceManager.GetString("URL_RESOURCE_bangbang93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://resources.download.minecraft.net/ 的當地語系化字串。
        /// </summary>
        internal static string URL_RESOURCE_BASE {
            get {
                return ResourceManager.GetString("URL_RESOURCE_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://mirrors.rapiddata.org/resources.download.minecraft.net/ 的當地語系化字串。
        /// </summary>
        internal static string URL_RESOURCE_rapiddata {
            get {
                return ResourceManager.GetString("URL_RESOURCE_rapiddata", resourceCulture);
            }
        }
    }
}
